export const CONTENT_LANGUAGES = [
  { code: "auto", label: "Auto-detect" },
  { code: "af", label: "Afrikaans" },
  { code: "ar", label: "العربية — Arabic" },
  { code: "hy", label: "Հայերեն — Armenian" },
  { code: "az", label: "Azərbaycanca — Azerbaijani" },
  { code: "be", label: "Беларуская — Belarusian" },
  { code: "bs", label: "Bosanski — Bosnian" },
  { code: "bg", label: "Български — Bulgarian" },
  { code: "ca", label: "Català — Catalan" },
  { code: "zh", label: "中文 — Chinese" },
  { code: "hr", label: "Hrvatski — Croatian" },
  { code: "cs", label: "Čeština — Czech" },
  { code: "da", label: "Dansk — Danish" },
  { code: "nl", label: "Nederlands — Dutch" },
  { code: "en", label: "English" },
  { code: "et", label: "Eesti — Estonian" },
  { code: "fi", label: "Suomi — Finnish" },
  { code: "fr", label: "Français — French" },
  { code: "gl", label: "Galego — Galician" },
  { code: "de", label: "Deutsch — German" },
  { code: "el", label: "Ελληνικά — Greek" },
  { code: "he", label: "עברית — Hebrew" },
  { code: "hi", label: "हिन्दी — Hindi" },
  { code: "hu", label: "Magyar — Hungarian" },
  { code: "is", label: "Íslenska — Icelandic" },
  { code: "id", label: "Bahasa Indonesia" },
  { code: "it", label: "Italiano — Italian" },
  { code: "ja", label: "日本語 — Japanese" },
  { code: "kn", label: "ಕನ್ನಡ — Kannada" },
  { code: "kk", label: "Қазақша — Kazakh" },
  { code: "ko", label: "한국어 — Korean" },
  { code: "lv", label: "Latviešu — Latvian" },
  { code: "lt", label: "Lietuvių — Lithuanian" },
  { code: "mk", label: "Македонски — Macedonian" },
  { code: "ms", label: "Bahasa Melayu — Malay" },
  { code: "mr", label: "मराठी — Marathi" },
  { code: "mi", label: "Māori" },
  { code: "ne", label: "नेपाली — Nepali" },
  { code: "no", label: "Norsk — Norwegian" },
  { code: "fa", label: "فارسی — Persian" },
  { code: "pl", label: "Polski — Polish" },
  { code: "pt", label: "Português — Portuguese" },
  { code: "ro", label: "Română — Romanian" },
  { code: "ru", label: "Русский — Russian" },
  { code: "sr", label: "Српски — Serbian" },
  { code: "sk", label: "Slovenčina — Slovak" },
  { code: "sl", label: "Slovenščina — Slovenian" },
  { code: "es", label: "Español — Spanish" },
  { code: "sw", label: "Kiswahili — Swahili" },
  { code: "sv", label: "Svenska — Swedish" },
  { code: "tl", label: "Tagalog" },
  { code: "ta", label: "தமிழ் — Tamil" },
  { code: "th", label: "ไทย — Thai" },
  { code: "tr", label: "Türkçe — Turkish" },
  { code: "uk", label: "Українська — Ukrainian" },
  { code: "ur", label: "اردو — Urdu" },
  { code: "vi", label: "Tiếng Việt — Vietnamese" },
  { code: "cy", label: "Cymraeg — Welsh" },
] as const;

export const WRITING_LANGUAGES = CONTENT_LANGUAGES.filter(
  language => language.code !== "auto"
);

export function languageLabel(code: string) {
  return (
    CONTENT_LANGUAGES.find(language => language.code === code)?.label ??
    code.toUpperCase()
  );
}
